# -*- coding: utf-8 -*-
"""Melike_Gebesoy_CapstoneProject.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GI8ueW5O1yZSco4f3y_PXKc0q4EXF7p8
"""

from google.colab import drive
drive.mount('/content/drive')

#Loading required libraries
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import scipy.stats as stats
import scipy.stats as st
import statsmodels.api as sm

import matplotlib.pyplot as plt
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.figure_factory as ff
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import accuracy_score, classification_report, roc_curve,precision_recall_curve, auc,confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

"""## Exploring Data"""

#reading dataset from drive
df = pd.read_csv("/content/drive/MyDrive/Sleep_health_and_lifestyle_dataset.csv")
df.head()

#obtaining info of the dataset
df.info()

df = df.drop("Person ID", axis=1)
df.head()

#checking the duplicated values
df.duplicated().sum()

#checking the missing values
df.isnull().sum()

#exploring the statistical measures
df.describe()

"""General Observations :

1) There are no missing values in the data.

2) The average age is 42.

3) There are no big difference between min and max values.

## EXPLORATORY DATA ANALYSIS

Questions to ask:


1) How is the sleep quality by gender?

2) Which gender has more sleep disorder?

3) How is the sleep quality by age group?

4) Which age group has more sleep disorder?

5) How is the relations between sleep quality and occupation?

6) How is the relations between sleep disorder and occupation?

7) Does stress levet affect sleep quality?

8) How is the relations between sleep quality and physical activity?

9) Is BMI a cause of sleep disorder?

10) How is the relations between sleep quality and blood pressure?

11) How is the relations between sleep quality and heart rate?

12} Can sleep quality and sleep duration be related?

13) Can sleep quality and sleep disorder be related?

## Answering the questions ##

# Let's try to figure how is the sleep quality by gender.
"""

#Let's see the pivot table first.

df.pivot_table("Quality of Sleep",columns=("Gender")) #By looking at the pivot table, we can understand that the sleep quality of women is better than men, with a slight difference.

#Now let's see these values ​​in the graph.
sns.boxplot(x="Quality of Sleep", y="Gender", data=df)

"""Why is sleep quality higher in women than men? We will look at the answer to this question below.

We now look at the relationship between sleep disorder and the gender.
"""

#I've grouped sleep disorders by gender


df.groupby(["Gender"])[["Sleep Disorder"]].value_counts() #According to this grouping, we see that women have more sleep disorders than men.

#And now we see that in graphs.

def gender_disorder(column):
  df_b = df.groupby([column, "Sleep Disorder"])["Gender"].count()
  df_b = df_b.unstack()
  return df_b.plot.bar(edgecolor=["k"])

gender_disorder("Gender")   #As we can see better in the graph, except for insomnia, women have more sleep disorders than men.
#By a very small margin, men have more insomnia than women.

"""# Let's look at the relationship between different age groups and sleep quality."""

#First, we divide the ages into groups.
#When we look at the data, we see that the youngest age is 27 and the oldest is 59.

age = pd.cut(df["Age"],[27,37,49,59]) #We divide ages into three groups, "27-37", "37-49", "49-59".

#First, we see the relationship between age groups and sleep quality in pivot table.

df.pivot_table("Quality of Sleep",columns=(age))  #We see in the table that the quality of sleep increases at the same rate as age increases.

#Now we see that in graph.


def age_dist(column):
  df_c = pd.cut(df["Age"],[27,37,49,59])
  df_s = df.groupby([column, df_c])["Quality of Sleep"].count()
  df_s = df_s.unstack()
  return df_s.plot.bar(edgecolor=["k"])

age_dist("Quality of Sleep")

"""We now look at the relationship between sleep disorder and the age groups."""

#I've grouped sleep disorders by age groups.

age = pd.cut(df["Age"],[27,37,49,59])
df.groupby([age])[["Sleep Disorder"]].value_counts() #When we look at the grouping, we see that sleep disorders are more common in middle and older ages.

#Now we see that in graph.

def age_dis(column):
  df_v = pd.cut(df["Age"],[27,37,49,59])
  df_n = df.groupby([column, df_v])["Sleep Disorder"].count()
  df_n = df_n.unstack()
  return df_n.plot.bar(edgecolor=["k"])

age_dis("Sleep Disorder")    #By looking at the graph, we can say that although sleep apnea is more common in the older age group, the middle age group has more sleep disorders.

"""## How is the relations between sleep quality and occupation? Let's look at the answer to this question.

"""

df.pivot_table("Quality of Sleep",columns=("Occupation"))

#Let's first look at the gender distribution of occupations.

def gender_d(column):
  df_g = df.groupby([column, "Gender"])["Occupation"].count()
  df_g = df_g.unstack()
  return df_g.plot.bar(edgecolor=["k"])

gender_d("Occupation")

#We look at the sleep quality graph of occupations by gender.

meslek = df.pivot_table(values="Quality of Sleep",index="Occupation",columns="Gender", aggfunc=np.mean)

meslek.plot(kind="bar", ylabel="Quality of Sleep").set(title="Mean Quality of Sleep for Occupations(Male vs Female)")
plt.tight_layout
plt.legend(bbox_to_anchor=(1.05,1),loc=2,borderaxespad=0.)
plt.show()

#First we look into the relations between sleep disorder and occupation.

df.groupby(["Occupation"])[["Sleep Disorder"]].value_counts()

def occupation(column):
  df_o = df.groupby([column, "Sleep Disorder"])["Occupation"].count()
  df_o = df_o.unstack()
  return df_o.plot.barh(edgecolor=["k"])

occupation("Occupation") #Female-dominated occupations (such as teachers, nurses) have more sleep disorders.

df.pivot_table("Quality of Sleep",columns=("Stress Level"))
#Looking at the pivot table, there is a negative correlation between the increase in stress level and the decrease in sleep quality.

#Now let's look at this correlation on the graph.


sns.regplot(x = "Quality of Sleep", y = "Stress Level", ci = None, line_kws={'linewidth':3, "color": "gray"}, data = df)

"""Now, based on the positive correlation of stress level with sleep quality, we look at our other inferences with this in mind."""

mlk = df.pivot_table(values="Stress Level",index="Occupation", columns="Sleep Disorder", aggfunc=("count",np.mean))
mlk

sns.heatmap(data=mlk["count"],cmap="magma_r",annot=True)
plt.show()

df.groupby("Gender")["Stress Level"].mean()

data = [4.675676,6.079365]
labels = ["Female", "Male"]

fig = plt.figure(figsize =(10, 7))
plt.pie(data, labels = labels, autopct="%1.1f%%")
plt.show()
#Men are more stressed than women.

sns.lmplot(data=df,x="Stress Level",y ="Quality of Sleep",hue="Gender",legend=False).set(title="Correlation between Stress Level and Quality of Sleep(Male vs Female)")
plt.legend(loc='upper right')
plt.tight_layout
plt.show()

#Stress has a stronger negative effect on women's sleep quality than on men's.

df.groupby([age])[["Stress Level"]].mean()

data = [6.008000,5.460526,4.447917]
labels = ["(27-37)", "(37-49)","(49-59)"]

fig = plt.figure(figsize =(10, 7))
plt.pie(data, labels = labels, autopct="%1.1f%%")
plt.show()

df.pivot_table("Quality of Sleep",columns=("Physical Activity Level"))

lpa = df.pivot_table(values="Quality of Sleep",index="Physical Activity Level", aggfunc=np.mean)

sns.set(rc = {'figure.figsize':(12,8)})
sns.set(font_scale=0.8)

lpa.plot(kind="bar", color = "lightblue" , width = 0.4, edgecolor=["w"], ylabel="Quality of Sleep", title="Mean Quality of Sleep for Physical Activities", legend = False)

plt.show()
#It is not possible to say that there is a relationship between physical activity level and sleep quality by looking at the graph.
#Of course, we can say that the quality of sleep increases as the level of physical activity increases, but it is not possible to say that there is a connection between them.

"""## BMI Category"""

#First, let's look at the data and numbers in the BMI category.

df["BMI Category"].value_counts()

#Now let's see them on piechart.

data = [195,148,21,10]
labels = ["Normal", "Overweight", "Normal Weight", "Obese"]

fig = plt.figure(figsize =(10, 7))
plt.pie(data, labels = labels, autopct="%1.1f%%")
plt.show()
#When we look at the piechart, we see that the participation among obese and normal weight people is less than the others.
#We will take these into consideration when making our inferences.

def bmi(column):
  df_i = df.groupby([column, "Sleep Disorder"])["BMI Category"].count()
  df_i = df_i.unstack()
  return df_i.plot.bar(edgecolor=["k"])

bmi("BMI Category")

#We can say that sleep disorders are more common among overweight people, but there is not enough clean data to establish a positive correlation here.

sns.set(font_scale=0.8)
sns.barplot(x="Sleep Disorder", y="Quality of Sleep",data=df, hue="BMI Category").set(title="The effect of BMI category and sleep quality on sleep disorder")
plt.show()

#In this graph, we look at the relationship between sleep disorder and sleep quality over the bmi category.
#We can easily say the effect of weight gain on sleep quality and sleep disorders by looking at this graph.

"""# What is the relationship between blood pressure and sleep quality? We are looking for an answer to this question."""

sdr = df.pivot_table(values="Quality of Sleep",index="Blood Pressure", aggfunc=np.mean)

sns.set(rc = {'figure.figsize':(12,8)})
sns.set(font_scale=0.8)

sdr.plot(kind="bar", color = "olive" , width = 0.4, edgecolor=["k"], ylabel="Quality of Sleep", title="Relations between Blood Pressure and Sleep Quality", legend = False)

plt.show()

#Looking at the graph, we can say that the relationship between blood pressure and sleep quality is unbalanced.

hrs = df.pivot_table(values="Quality of Sleep",index="Heart Rate", aggfunc=np.mean)

sns.set(rc = {'figure.figsize':(12,8)})
sns.set(font_scale=0.8)

hrs.plot(kind="bar", color = "darkgray" , width = 0.4, edgecolor=["k"], ylabel="Quality of Sleep", title="Relations between Heart Rate and Sleep Quality", legend = False)

plt.show()
#Looking at the graph, we can say that the relationship between heart rate and sleep quality is unbalanced.

"""## We are looking the relations between sleep duration and sleep quality."""

sns.regplot(x = "Sleep Duration",y = "Quality of Sleep",ci = None, scatter_kws={"color": "red"}, line_kws={"color": "darkgray"}, data = df)

#We can say that there is a positive correlation between sleep duration and sleep quality.

#Now let's look at this relationship through sleep disorder.
sns.lmplot(data=df, x="Sleep Duration", y ="Quality of Sleep", hue="Sleep Disorder", legend=False).set(title="Correlation between Sleep Duration and Quality(Sleep Disorders)")

plt.legend(loc="upper left")
plt.show()

#In this graph, we look at the relationship between sleep quality and sleep disorder.
#We looked at the relationships between sleep quality and sleep disturbance in gender and age groups and found that they were inversely proportional.
#As we can see here too, it is not possible to say that sleep quality has an effect on sleep disorder.

omg = df.pivot_table(values="Quality of Sleep",index="Sleep Disorder",aggfunc=np.mean)

sns.set(rc = {'figure.figsize':(8,6)})
sns.set(font_scale=0.8)

omg.plot(kind="bar", color = "darkblue" , width = 0.1, edgecolor=["k"], ylabel="Quality of Sleep", title="Mean Quality of Sleep for Sleep Disorder", legend = False)

plt.show()

"""To sum Up

*   We can say that there is a negative correlation between Stress Level and Sleep Quality. That's why women's sleep quality is higher than men's.
*   Unfortunately there are some columns that we can not correlated in any ways.
*   However there are so many graphs that we can make inferences.
*   We can associate gender, age, occupation, sleep duration with sleep quality and sleep disorder.


"""